#!/usr/bin/env python3

import os

import subprocess

import serial.tools.list_ports




# Official Hardware IDs restored from original


UBLOX_VID = 0x1546  # u-blox AG


ESP32_VID = 0x303a  # Espressif Systems (ESP32-S3)





def sanitize_hardware(port):


    """The 'Sane' Reset: Kills zombies and fixes ASIO latency at the kernel level."""


    if not port or port == "virtual":


        return


    


    print(f"🛠️  Sanitizing {port}...")


    try:


        # 1. Kill zombie processes (fuser)


        subprocess.run(["sudo", "fuser", "-k", port], stderr=subprocess.DEVNULL)


        


        # 2. Set low latency mode (Stops thousands of ASIO errors)


        subprocess.run(["sudo", "setserial", port, "low_latency"], stderr=subprocess.DEVNULL)


        


        # 3. Force baud and raw mode (Prevents kernel from 'interpreting' binary data)


        subprocess.run(["sudo", "stty", "-F", port, "460800", "raw", "-echo"], stderr=subprocess.DEVNULL)


        


        # 4. Ensure permissions


        subprocess.run(["sudo", "chmod", "666", port], stderr=subprocess.DEVNULL)


    except Exception as e:


        print(f"⚠️  Warning during sanitization of {port}: {e}")



def scan_and_export():


    print("🔎 Scanning for Open Agbot Hardware...")

    ports = serial.tools.list_ports.comports()


    


    gps_device = None


    mcu_device = None





    # Precise scanning based on Vendor ID


    for port in ports:


        if port.vid == UBLOX_VID:


            gps_device = port.device


            print(f"✅ Found u-blox GPS: {gps_device}")


        elif port.vid == ESP32_VID:


            mcu_device = port.device


            print(f"✅ Found ESP32 MCU:  {mcu_device}")





    # ACTIVE SANITIZATION: Fix the kernel buffers before writing .env


    if gps_device:


        sanitize_hardware(gps_device)


    if mcu_device:


        sanitize_hardware(mcu_device)




    # Determine status for logs


    gps_status = f"✅ FOUND ({gps_device})" if gps_device else "👻 GHOST (Not Connected)"


    mcu_status = f"✅ FOUND ({mcu_device})" if mcu_device else "👻 GHOST (Not Connected)"


    


    print(f"MCU Status: {mcu_status}")


    print(f"GPS Status: {gps_status}")




    # Write to .env (Syntax preserved exactly)

    env_path = os.path.join(os.getcwd(), ".env")


    try:


        with open(env_path, "w") as f:


            f.write("# Auto-generated by fixusb.py with restored VID scanning\n")


            f.write(f"GPS_PORT={gps_device if gps_device else 'virtual'}\n")


            f.write(f"MCU_PORT={mcu_device if mcu_device else 'virtual'}\n")


            f.write(f"USER_ID={os.getuid()}\n")


            f.write(f"GROUP_ID={os.getgid()}\n")


        print(f"✨ .env file updated successfully at {env_path}")


    except Exception as e:


        print(f"❌ Failed to write .env file: {e}")



if __name__ == "__main__":

    scan_and_export()
