#!/usr/bin/env python3
import os
import serial.tools.list_ports

# Official Hardware IDs restored from original
UBLOX_VID = 0x1546  # u-blox AG
ESP32_VID = 0x303a  # Espressif Systems (ESP32-S3)

def scan_and_export():
    print("🔎 Scanning for Open Agbot Hardware...")
    ports = serial.tools.list_ports.comports()
    
    # Defaults if not found
    gps_device = None
    mcu_device = None

    # Precise scanning based on Vendor ID
    for port in ports:
        if port.vid == UBLOX_VID:
            gps_device = port.device
            print(f"✅ Found u-blox GPS: {gps_device}")
        elif port.vid == ESP32_VID:
            mcu_device = port.device
            print(f"✅ Found ESP32 MCU:  {mcu_device}")

    # Determine status for logs
    gps_status = f"✅ FOUND ({gps_device})" if gps_device else "👻 GHOST (Not Connected)"
    mcu_status = f"✅ FOUND ({mcu_device})" if mcu_device else "👻 GHOST (Not Connected)"
    
    print(f"MCU Status: {mcu_status}")
    print(f"GPS Status: {gps_status}")

    # Write to .env
    env_path = os.path.join(os.getcwd(), ".env")
    try:
        with open(env_path, "w") as f:
            f.write("# Auto-generated by fixusb.py with restored VID scanning\n")
            # If not found, we use 'virtual' or leave empty so manage.py knows to sim
            f.write(f"GPS_PORT={gps_device if gps_device else 'virtual'}\n")
            f.write(f"MCU_PORT={mcu_device if mcu_device else 'virtual'}\n")
            # Dynamically fetch IDs to prevent Docker permission errors
            f.write(f"USER_ID={os.getuid()}\n")
            f.write(f"GROUP_ID={os.getgid()}\n")
        print(f"✨ .env file updated successfully at {env_path}")
    except Exception as e:
        print(f"❌ Failed to write .env file: {e}")

    # Security: Ensure ports are readable if they exist
    for dev in [gps_device, mcu_device]:
        if dev and os.path.exists(dev):
            # Check if we have read/write access, if not, warn the user
            if not os.access(dev, os.R_OK | os.W_OK):
                print(f"🔐 Permission Denied on {dev}. Suggest: sudo chmod 666 {dev}")

if __name__ == "__main__":
    scan_and_export()
